version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - ./app:/app
    command: >
      bash -c "cp /tmp/container_install.sh /app/install.sh && git clone https://github.com/tsnlab/connx.git" 


